### ISSUE TITLE
[studio] publish failing due to message expansion error

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1025]
```
[ERROR] 2017-06-23 15:08:34,271 [studioSchedulerFactoryBean_Worker-6] [git.GitContentRepository] | Cherry-pick failed {site/website/style/test/health-renamed-c/.keep=DIRTY_INDEX} and arguments [Ljava.lang.Object;@76dfeed0 failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/test/health-renamed-c/.keep=DIRTY_INDEX

[ERROR] 2017-06-23 15:08:34,285 [studioSchedulerFactoryBean_Worker-6] [git.GitContentRepository] | Cherry-pick failed {site/website/style/test/health-renamed-c/.keep=DIRTY_INDEX} and arguments [Ljava.lang.Object;@101629dc failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/test/health-renamed-c/.keep=DIRTY_INDEX
```

**Comment by russdanner** [comment]
UI reports published status via icon

No file shows up in published folder

git status shows items in status

**Comment by russdanner** [comment]
Trying to reproduce the error in a clean blueprint.  I never touched any repo manually but I've been copy-paste-renaming things all morning.

**Comment by sumerjabri** [comment]
@russdanner 
* please attach `git status` output.
* Do you happen to have steps to reproduce?

**Comment by russdanner** [comment]
```
➜  website git:(live) ✗ git status
On branch live
Your branch and 'master' have diverged,
and have 16 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
You are currently cherry-picking commit 035cb10.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	renamed:    style/test/health-renamed/folder-x/entertainment/health/.keep -> style/test/health-renamed-c/.keep
	renamed:    style/test/health-renamed/folder-x/entertainment/.keep -> style/test/health-renamed-c/folder-x/.keep
	renamed:    style/test/health-renamed/folder-x/.keep -> style/test/health-renamed-c/folder-x/entertainment/.keep
	renamed:    style/test/health-renamed/.keep -> style/test/health-renamed-c/folder-x/entertainment/health/.keep
	renamed:    style/test/health-renamed/folder-x/entertainment/health/index.xml -> style/test/health-renamed-c/folder-x/entertainment/health/index.xml
	renamed:    style/test/health-renamed/folder-x/entertainment/index.xml -> style/test/health-renamed-c/folder-x/entertainment/index.xml
	new file:   style/test/health-renamed-c/index.xml

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: style/test/health-renamed/index.xml

```

**Comment by russdanner** [comment]
# reproducing the error
1. under home create a page called A
2. publish A
3. Under A create a page called B
4. Rename A to A-RENAMED
5. Publish B.  

Note:  that A is not shown as a dependency as it should in the dialog
On publish error is thrown but has a null in it: 
`[ERROR] 2017-06-23 15:25:44,209 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Conflict executing cherry-pick null`

and items will show up in published repo uncommitted:
```
➜  site git:(live) git status
On branch live
Your branch and 'master' have diverged,
and have 2 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
You are currently cherry-picking commit 0400ae7.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Changes to be committed:

	new file:   website/a-rename/.keep
	new file:   website/a-rename/b/.keep
	new file:   website/a-rename/b/index.xml
	new file:   website/a-rename/index.xml

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: website/a/index.xml

```

**Comment by sumerjabri** [comment]
@dejan-brkic we need to fix in this order:
1. reproduce and then fix the message expansion
2. reproduce and then fix the dep calc
3. reproduce and then fix the publishing error

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/762

**Comment by russdanner** [comment]
Tested.  No error emerges but there is still an issue with this scenario.

Items now publish.  The renamed folder (A) gets published but the old A is not removed from the published repository:

<img width="1427" alt="screen shot 2017-07-10 at 12 39 39 pm" src="https://user-images.githubusercontent.com/169432/28029211-4501605c-656d-11e7-965f-e652e614992b.png">

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/781

**Comment by russdanner** [comment]
# Issue still exists. Original test case still failing
```
under home create a page called A
publish A
Under A create a page called B
Rename A to A-RENAMED
Publish B.
Note: that A is still in the published repository
```

<img width="1306" alt="screen shot 2017-07-12 at 4 19 02 pm" src="https://user-images.githubusercontent.com/169432/28138455-d6f68868-671e-11e7-8c94-0964f10e59e0.png">

**Comment by dejan-brkic** [comment]
Can not reproduce issue with latest builds

**Comment by russdanner** [comment]
Verified
