### ISSUE TITLE
[studio] Use the user's time zone as the basis for scheduled publishing

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#1316]
Using a system with the time zone set to Pacific time and the Website_editorial bp, edit a page and save.  Publish the page to a later time, say 30 minutes later.

![screen shot 2017-09-07 at 10 17 06 am](https://user-images.githubusercontent.com/25483966/30167977-15328f96-93b6-11e7-8e5c-2a2e34378970.png)

Notice that the page is immediately published, instead of the time specified.

![screen shot 2017-09-07 at 10 18 03 am](https://user-images.githubusercontent.com/25483966/30168086-63768c66-93b6-11e7-94a1-d1033be4da9c.png)

Here's a short clip showing the page being published immediately after scheduling instead of an hour later:

https://www.useloom.com/share/b2d5ed2271334c30ada41bcfd2730fab

**Comment by sumerjabri** [comment]
@dejan-brkic let's discuss before you build.

**Comment by dejan-brkic** [comment]
Schedule dialog by default schedules using 'EST5EDT' time zone. Keeping that in mind, it makes sense if content is scheduled in few minutes ahead on system set to Pacific time, because of time zone conversion, time set in the dialog is actually behind the current time so it will get published immediately. So the system behaves correctly.
Real question is what is desired behavior in terms of time zones and displayed time in the dialog. Additional problem also seems to be that scheduled items dashboard seems to display incorrect time.

@sumerjabri i think we need to spec these time zone confusion.

**Comment by sumerjabri** [comment]
Here is what I want:
I want the UI to show all times per user's tz.
I want the system to store everything as UTC.

Crafter CMS internally will only know of 1 timezone, UTC. The UI will always convert everything to UTC before it sends to the backend, and convert from UTC to local before displaying to the user.

The downside is that API users will have to be made aware of this.

Advantage: 0 confusion down the road.

What do you think?

**Comment by dejan-brkic** [comment]
Done
PR:
UI https://github.com/craftercms/studio-ui/pull/587
Backend https://github.com/craftercms/studio/pull/858

**Comment by alhambrav** [comment]
Still the same behavior as mentioned in the ticket for a Windows 10 OS.  Using OSX,it's working okay with scheduling.

The system I used is in Pacific time.  I built craftercms around 11am, below is the version of Studio I am using.

![screen shot 2017-09-15 at 2 44 12 pm](https://user-images.githubusercontent.com/25483966/30498407-a5fc5b0a-9a24-11e7-9922-02022e5a3254.png)

I made some changes in the Home page, and scheduled it to be published some time later.

![screen shot 2017-09-15 at 2 45 00 pm](https://user-images.githubusercontent.com/25483966/30498417-abd2e738-9a24-11e7-842f-774fb814f023.png)

The changes got published immediately.
![screen shot 2017-09-15 at 2 46 02 pm](https://user-images.githubusercontent.com/25483966/30498428-b13e130a-9a24-11e7-9cf0-369545c43416.png)

**Comment by dejan-brkic** [comment]
As i mentioned above, Schedule dialog defaults to EST5EDT timezone. When scheduling if user (Pacific time) does not change timezone in dialog, content will be published immediately if scheduled with next few minutes due to time conversion between default dialog timezone and system zone.
If user changes timezone in the dialog, to takes in account time difference, schedule works as expected.
Issue is not in backend. This issues is caused because Schedule defaults to EST5EDT time zone.

**Comment by dejan-brkic** [comment]
Behavior verified both on OS X and Windows 10 and it behaves exactly same in both environments and with different timezones (EST5EDT, PST, CEST)

**Comment by alhambrav** [comment]
Verified fixed.
