### ISSUE TITLE
[studio] Publishing renamed/moved item does not clean old path from published sandbox

### ISSUE THREAD

**Issue by dejan-brkic** [craftercms/craftercms#1709]
### Expected behavior
Publishing renamed/moved item should publish item at new location and delete it from old location

### Actual behavior
Publishing renamed/moved item does not delete file from the old location

### Steps to reproduce the problem
* Create site from editorial BP
* Rename existing page
* Publish page
* Error: file on the old location in published sandbox is not deleted

### Log/stack trace (use https://gist.github.com)
No errors in start trace

### Specs: version, OS, browser, etc.
Latest version, all OS, all browsers

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/988

**Comment by sumerjabri** [comment]
There is still an issue. Steps:
* Create a site using editorial bp
* Rename /articles/2017 to /articles/2017-2
* From the dashboard, show in-progress items and publish all articles
* On disk, go to `published` and run the command `diff -r --exclude ".git" . ../sandbox` and you'll see:
```
Only in ./site/website/articles: 2017
Only in ../sandbox/site/website/articles/2017-2/1: .keep
Only in ../sandbox/site/website/articles/2017-2/1/men-styles-for-winter: .keep
Only in ../sandbox/site/website/articles/2017-2/1/women-styles-for-winter: .keep
Only in ../sandbox/site/website/articles/2017-2/2/10-tips-to-get-a-six-pack: .keep
Only in ../sandbox/site/website/articles/2017-2/2: .keep
Only in ../sandbox/site/website/articles/2017-2/2/top-romantic-valentine-movies: .keep
Only in ../sandbox/site/website/articles/2017-2/3/5-popular-diets-for-women: .keep
Only in ../sandbox/site/website/articles/2017-2/3: .keep
Only in ../sandbox/site/website/articles/2017-2/3/top-clubs-in-virginia: .keep
Only in ../sandbox/site/website/articles/2017-2: .keep
```

Note the `.keep`s are keeing things behind.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/998

**Comment by sumerjabri** [comment]
Same steps to reproduce. Here is what I see on disk:
```
sumer@xinu:/home/sumer/code/crafter/craftercms/crafter-authoring/data/repos/sites/asdf  git:(develop) $ find . -name '2017*'
./published/site/website/articles/2017-2
./published/site/website/articles/2017
./sandbox/site/website/articles/2017-2
```

```sumer@xinu:/home/sumer/code/crafter/craftercms/crafter-authoring/data/repos/sites/asdf  git:(develop) $ tree published/site/website/articles/2017                                     
published/site/website/articles/2017
├── 1
│   ├── men-styles-for-winter
│   │   └── index.xml
│   └── women-styles-for-winter
│       └── index.xml
├── 2
│   ├── 10-tips-to-get-a-six-pack
│   │   └── index.xml
│   └── top-romantic-valentine-movies
│       └── index.xml
└── 3
    ├── 5-popular-diets-for-women
    │   └── index.xml
    └── top-clubs-in-virginia
        └── index.xml

9 directories, 6 files
```

**Comment by dejan-brkic** [comment]
Can not reproduce it with steps described above
```
Studio Version Number: 3.0.4-SNAPSHOT-b41cd2
Build Number: b41cd226e1ffef32ccf6971a2d217d569d078451
```
