### ISSUE TITLE
[studio] 2.5.x dependency dialog showing wrong results

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1811]
### Expected behavior
Dependency dialog should show correct results for the item requested on both refers to and referenced by views

### Actual behavior
https://www.useloom.com/share/762798c2f9ee468dba0a65c5f4734fa6

### Steps to reproduce the problem
* Use dependency dialog on item with simple dependencies
* not issues identified in video
*

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1025

**Comment by russdanner** [comment]
Refers to looks better
Item in dialog is still wrong
Referenced by still looks wrong
https://www.useloom.com/share/f2643e457627474fbc80d33b1864f5a4

**Comment by dejan-brkic** [comment]
This is UI issue now. I have analyzed the execution of that dialog. It first calls get-dependnecies service, which now gives a flat response (all dependencies as an array) and then picks probably first in unsorted list/array. After that, it makes another call depending on what dependency direction is selected. The first call get-dependencies is absolutely unnecessary and wrong (maybe is get content item needed). get-dependencies will return publishing dependencies and it is used in workflow dialogs.

**Comment by jvega-crafter** [comment]
https://github.com/craftercms/studio-ui/pull/756

**Comment by jvega-crafter** [comment]
@russdanner Removed unnecesary extra dependencies calls, need to test dependencies service, shows some items that seems that doesn't belong (itself twice, etc). Please let me know if there's something else needed in UI

**Comment by russdanner** [comment]
VERIFIED
