### ISSUE TITLE
[studio] deleting a folder does not delete the folder or its child items in the environment store

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#1834]
### Expected behavior
deleting a folder should cause a cascade delete of all objects under it
Item-specific dependencies (recursive) should be calculated for all children of the folder as well and delete as well.

### Actual behavior
The folder and all its children remain in the environment store
https://www.useloom.com/share/1d44107973a94936924173b00f1c0410

### Steps to reproduce the problem
* create a folder 
* create an item in the folder
* delete the folder
* not the delete is not reflected in the environment store

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1032

**Comment by russdanner** [comment]
VERIFIED.  Minor bug still exists when deleting a page tree requires 2 deletes first of the page then the folder.  The UI is out of sync with the server behavior.  No need to hold the release for this issue.
I will open a second ticket.
https://www.useloom.com/share/daf3494703a245e384482a3b790e105d
