### ISSUE TITLE
[Studio] User and Groups apis issues

### ISSUE THREAD

**Issue by vestrada** [craftercms/craftercms#2427]
### Expected behavior
User and Groups apis  

### Actual behavior
**USER APIS**

- DELETE User
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/users/deleteUser

![image](https://user-images.githubusercontent.com/11640613/45107127-d150a700-b0f5-11e8-964d-f8023ff0e24c.png)

`[ERROR] 2018-09-05 10:06:31,935 [http-nio-8080-exec-7] [impl.DefaultExceptionHandler] | DELETE http://localhost:8080/studio/api/2/users?id=6 failed 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:894)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:667)
`

**Groups APIS**

- GET /groups/{id}/members
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/groups/getGroupMembers  
Parameters are still required

`[ERROR] 2018-09-05 10:52:55,230 [http-nio-8080-exec-4] [impl.DefaultExceptionHandler] | GET http://localhost:8080/studio/api/2/groups/14/members failed 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Optional int parameter 'offset' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type.
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
`

- POST /groups/{id}/members
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/groups/addGroupMembers

![image](https://user-images.githubusercontent.com/11640613/45108716-9f8e0f00-b0fa-11e8-87ca-42cd62c508bd.png)

`[ERROR] 2018-09-05 10:59:30,218 [http-nio-8080-exec-6] [impl.DefaultExceptionHandler] | POST http://localhost:8080/studio/api/2/groups/14/members failed 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.DuplicateKeyException: 
Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: (conn:12) Duplicate entry '2-14' for key PRIMARY`

- DELETE Group: 
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/groups/deleteGroup
I'm getting 400 as a response, but the groups aren't removed.

- I can't check:  DELETE /groups/{id}/members

**OTHER ISSUES**

-Reset password, create site: are Getting: 401 error.

#### Version
Studio Version Number: 3.1.0-SNAPSHOT-52aae7
Build Number: 52aae7006cd3c563d6e1baa2c97d88ee5384e74d
Build Date/Time: 09-04-2018 13:46:28 -0600

#### OS
Mac

#### Browser
All Browsers

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio/pull/1243

**Comment by vestrada** [comment]
Hi dejan

I'm still getting errors from:

- POST /groups/{id}/members
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/groups/addGroupMembers

![image](https://user-images.githubusercontent.com/11640613/45188298-042b9580-b1f1-11e8-89b6-0a7b2a8625e1.png)

- DELETE Group:
Please check: https://app.swaggerhub.com/apis/craftercms/studio/2#/groups/deleteGroup
I'm getting 400 as a response, but the groups aren't removed.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1249
