### ISSUE TITLE
[studio] Error making go live 

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3036]
## Describe the bug
There's an error in the logs when you schedule a page to be published and the dialog for scheduling does not go away until you refresh your browser 

## To Reproduce
1. Create a site using website_editorial bp
2. Edit the `Home` page and save your changes
3. Click on `Approve & Publish` or `Schedule` from the context nav and pick a date and time to publish later
![Screen Shot 2019-04-04 at 2 23 50 PM](https://user-images.githubusercontent.com/25483966/55579132-95121300-56e5-11e9-9b4f-c801e1650d9a.png)

4. Click on `Submit`, notice the dialog does not go away
![Screen Shot 2019-04-04 at 2 21 14 PM](https://user-images.githubusercontent.com/25483966/55578879-eff73a80-56e4-11e9-9a9a-a1350c735e4b.png)
5. View the logs and notice the error there.  See the Logs section to see the stacktrace
```
ERROR] 2019-04-04T14:17:23,596 [http-nio-8080-exec-2] [workflow.WorkflowServiceImpl] | error making go live
org.springframework.dao.DataIntegrityViolationException:
### Error updating database.  Cause: java.sql.SQLDataException: (conn:8) Data too long for column 'operation' at row 1
```

Note that the page appears to be published okay, even if there were errors in the log.

## Expected behavior
There should be no error in the logs when scheduling an item to be published and the scheduling dialog should go away

## Screenshots
Here's a short clip showing the scheduling dialog stuck (after the 30 second mark in the video, it's just showing that the dialog does not go away even if you wait for a while):
https://www.useloom.com/share/2ddadfa39da945a99e0ae107a5c972bf

## Logs
https://gist.github.com/alhambrav/b1fe41cae1e00d773c7540cdf36d0338

### Version
Studio Version Number: 3.1.0-SNAPSHOT-3e88c1
Build Number: 3e88c1e7b4fa79b7ca0e2569eb59196bff02c603
Build Date/Time: 04-04-2019 14:09:07 -0400

### OS
OS X

### Browser
Chrome browser

**Comment by dejan-brkic** [comment]
Fixed with this PR:
https://github.com/craftercms/studio/pull/1551

**Comment by alhambrav** [comment]
@dejan-brkic I still see the error in the logs
https://gist.github.com/alhambrav/1530293e6aa9995f8b357a4f97a8d600

##Version
Studio Version Number: 3.1.0-SNAPSHOT-827427
Build Number: 82742775dfdc8988b32ecb6793f73480ee69c887
Build Date/Time: 04-09-2019 07:10:32 -0400

**Comment by alhambrav** [comment]
Verified fixed.
