### ISSUE TITLE
[studio] Studio fails to start after an upgrade from 3.1.0 to develop

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#3320]
## Describe the bug
Studio fails to start after upgrade from 3.1.0 to develop ` Incompatible database detected, unable to start` 

## To Reproduce
1. Download and run a `3.1.0` authoring bundle
2. Create a bundle from `develop` 
3. Follow the guide https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html#upgrading-crafter-cms-installed-from-a-bundle
4. During the upgrade use the option ` - (A)lways delete the file and and don't ask again for the rest of the upgrade` and ` - (A)lways overwrite files and don't ask again for the rest of the upgrade`
5. Start up authoring

## Expected behavior
Authoring starts up successfully. 

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
https://gist.github.com/yacdaniel/6c1bcc4a7ba27b7f1599abe325c269d1

### Version
Studio Version Number: 3.1.1-SNAPSHOT-d2a6e6
Build Number: d2a6e6c226aeff2ad39293a4389f408b6d7b9e55
Build Date/Time: 07-29-2019 17:10:05 -0600

### OS
Linux

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/commons/pull/180

**Comment by yacdaniel** [comment]
@dejan-brkic this im what im getting when upgrading following the guide.
```
[o] Overwriting config file apache-tomcat/conf/catalina.policy with the new release version (backup of the old one will be at apache-tomcat/conf/catalina.policy.20190807145244.bak)                                                                                         
> Upgrade database? [(Y)es/(N)o]: Yes                                                                                                                                                              
========================================================================                                                                                                                                                                  
Upgrade database                                                                                                                                                                                                                                                               
========================================================================                                                                                                                               
------------------------------------------------------------------------                                                                                                                                                                          
Starting upgrade database /home/yacdaniel/prerelease/crafter/data/db                                                                                                                                                                              
------------------------------------------------------------------------                                                                                                                                                                                        
------------------------------------------------------------------------                                                                                                             
Starting DB                                                                                                                                                                                      
------------------------------------------------------------------------                                                                                                                                                                                        
2019-08-07 14:52:50.077  INFO 12107 --- [           main] c.v.m.s.boot.MariaDB4jApplication        : Starting MariaDB4jApplication on docker with PID 12107 (/home/yacdaniel/prerelease/crafter/bin/mariaDB4j-app.jar started by yacdaniel in /home/yacdaniel/prerelease/crafte
r/bin)                                                                                                                                                                                
2019-08-07 14:52:50.080  INFO 12107 --- [           main] c.v.m.s.boot.MariaDB4jApplication        : No active profile set, falling back to default profiles: default                                              
2019-08-07 14:52:50.815  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : Created directory: /home/yacdaniel/prerelease/crafter/bin/dbms/libs                                                               
2019-08-07 14:53:02.534  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : Unpacked 82 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.4.6/linux/** to /home/yacdaniel/prerelease/crafter/bin/dbms                            
2019-08-07 14:53:02.536  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/my_print_defaults (using java.io.File.setExecutable)
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_install_db (using java.io.File.setExecutable)
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/scripts/mysql_install_db (using java.io.File.setExecutable)                                           
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld (using java.io.File.setExecutable)                                                                        
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqldump (using java.io.File.setExecutable)
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql (using java.io.File.setExecutable)
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x requested on non-existing file: /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_upgrade                                   
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqlcheck (using java.io.File.setExecutable)                         
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.Util              : chmod +x /home/yacdaniel/prerelease/crafter/bin/dbms/bin/resolveip (using java.io.File.setExecutable)        
2019-08-07 14:53:02.537  INFO 12107 --- [           main] ch.vorburger.mariadb4j.DB                : Installing a new embedded database to: /home/yacdaniel/prerelease/crafter/bin/dbms                          
2019-08-07 14:53:02.551  INFO 12107 --- [           main] ch.vorburger.exec.ManagedProcess         : Starting Program [/home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_install_db, --datadir=/home/yacdaniel/prerelease/crafter/data/db, --basedir=/home/yacdaniel/prerel
ease/crafter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /home/yacdaniel/prerelease/crafter/bin/dbms)                                                                 
2019-08-07 14:53:02.575  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysql_install_db: mysql.user table already exists!                                                   
2019-08-07 14:53:02.575  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysql_install_db: Run mysql_upgrade, not mysql_install_db                                        
2019-08-07 14:53:02.576  INFO 12107 --- [efault Executor] c.v.exec.LoggingExecuteResultHandler     : Program [/home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_install_db, --datadir=/home/yacdaniel/prerelease/crafter/data/db, --basedir=/home/yacdaniel/prerelease/craf
ter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /home/yacdaniel/prerelease/crafter/bin/dbms) just exited, with value 0                                                    
2019-08-07 14:53:02.654  INFO 12107 --- [           main] ch.vorburger.exec.ManagedProcess         : Thread is now going to wait for this process to terminate itself: Program [/home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_install_db, --datadir=/home/yacdaniel/pre
release/crafter/data/db, --basedir=/home/yacdaniel/prerelease/crafter/bin/dbms, --no-defaults, --force, --skip-name-resolve] (in working directory /home/yacdaniel/prerelease/crafter/bin/dbms)
2019-08-07 14:53:02.654  INFO 12107 --- [           main] ch.vorburger.mariadb4j.DB                : Installation complete.                                                                                                                                                    
2019-08-07 14:53:02.655  INFO 12107 --- [           main] ch.vorburger.mariadb4j.DB                : Starting up the database...                         
2019-08-07 14:53:02.656  INFO 12107 --- [           main] ch.vorburger.mariadb4j.DB                : mysqld executable: /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld
2019-08-07 14:53:02.656  INFO 12107 --- [           main] ch.vorburger.exec.ManagedProcess         : Starting Program [/home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/home/yacdani
el/prerelease/crafter/bin/dbms, --datadir=/home/yacdaniel/prerelease/crafter/data/db, --port=33306, --socket=/tmp/mysql.sock] (in working directory /home/yacdaniel/prerelease/crafter/bin/dbms)                                                                               
2019-08-07 14:53:02.657  INFO 12107 --- [           main] ch.vorburger.exec.ManagedProcess         : Thread will wait for "mysqld: ready for connections." to appear in Console output of process Program [/home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld, --no-default
s, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/home/yacdaniel/prerelease/crafter/bin/dbms, --datadir=/home/yacdaniel/prerelease/crafter/data/db, --port=33306, --socket=/tmp/mysql.sock] (in working directory /home/yacdaniel/prerelease/crafter/bin/
dbms) for max. 30000ms                                                                                                                                                                         
2019-08-07 14:53:02.773  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld (mysqld 10.4.6-MariaDB) starting as process 12157 ...
2019-08-07 14:53:02.805  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Using Linux native AIO
2019-08-07 14:53:02.805  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-08-07 14:53:02.805  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Uses event mutexes                                                                                                           
2019-08-07 14:53:02.805  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Compressed tables use zlib 1.2.11             
2019-08-07 14:53:02.805  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Number of pools: 1                                                                                                           
2019-08-07 14:53:02.806  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Using SSE2 crc32 instructions                                                                                                
2019-08-07 14:53:02.806  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2019-08-07 14:53:02.807  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M                       
2019-08-07 14:53:02.813  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Completed initialization of buffer pool
2019-08-07 14:53:02.814  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-08-07 14:53:02.836  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Upgrading redo log: 2*50331648 bytes; LSN=3755590
2019-08-07 14:53:02.939  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Starting to delete and rewrite log files.
2019-08-07 14:53:02.954  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Setting log file ./ib_logfile101 size to 50331648 bytes                                                                      
2019-08-07 14:53:02.954  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Setting log file ./ib_logfile1 size to 50331648 bytes
2019-08-07 14:53:02.968  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0                                              
2019-08-07 14:53:02.968  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: New log files created, LSN=3755590                                                              
2019-08-07 14:53:02.970  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-08-07 14:53:02.970  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Creating sys_virtual system tables.                                                                                        
2019-08-07 14:53:02.972  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Creating shared tablespace for temporary tables  
2019-08-07 14:53:02.972  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-08-07 14:53:02.972  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.                                                                                           
2019-08-07 14:53:02.975  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:02 0 [Note] InnoDB: Waiting for purge to start                           
2019-08-07 14:53:03.027  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] InnoDB: 10.4.6 started; log sequence number 3755590; transaction id 16901                               
2019-08-07 14:53:03.027  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] InnoDB: Loading buffer pool(s) from /home/yacdaniel/prerelease/crafter/data/db/ib_buffer_pool           
2019-08-07 14:53:03.027  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] InnoDB: Cannot open '/home/yacdaniel/prerelease/crafter/data/db/ib_buffer_pool' for reading: No such file or directory
2019-08-07 14:53:03.028  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] Plugin 'FEEDBACK' is disabled.             
2019-08-07 14:53:03.028  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] Server socket created on IP: '::'.                     
2019-08-07 14:53:03.030  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 6 [Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade
2019-08-07 14:53:03.030  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 6 [Warning] InnoDB: Table mysql/innodb_index_stats has length mismatch in the column name table_name.  Please run mysql_upgrade               
2019-08-07 14:53:03.031  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] Reading of all Master_info entries succeeded
2019-08-07 14:53:03.031  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] Added new Master_info '' to hash table                                   
2019-08-07 14:53:03.031  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: 2019-08-07 14:53:03 0 [Note] /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysqld: ready for connections.               
2019-08-07 14:53:03.031  INFO 12107 --- [c Stream Pumper] ch.vorburger.exec.ManagedProcess         : mysqld: Version: '10.4.6-MariaDB'  socket: '/tmp/mysql.sock'  port: 33306  MariaDB Server                                                                  
2019-08-07 14:53:03.058  INFO 12107 --- [           main] ch.vorburger.mariadb4j.DB                : Database startup complete.                                                                                   
2019-08-07 14:53:03.384  INFO 12107 --- [           main] c.v.m.s.boot.MariaDB4jApplication        : Started MariaDB4jApplication in 13.737 seconds (JVM running for 14.154)                                     
------------------------------------------------------------------------                                                                                                                                                                                        
Upgrade mysql                                                                                                                                                                                                                                                                  
------------------------------------------------------------------------                                                                                                                                  
./crafter.sh: line 957: /home/yacdaniel/prerelease/crafter/bin/dbms/bin/mysql_upgrade: No such file or directory                                                                                      
Unable to continue, an error occurred or the script was forcefully stopped                                                                                                                                                                    
Caught: java.lang.RuntimeException: Process '[./crafter.sh, upgradedb]' exited with non-successful value 1                                                                                                                          
java.lang.RuntimeException: Process '[./crafter.sh, upgradedb]' exited with non-successful value 1                                                                                                                
        at utils.ScriptUtils.executeCommand(ScriptUtils.groovy:79)                                                                                                                                               
        at utils.ScriptUtils.executeCommand(ScriptUtils.groovy:55)                                                                                                                                                                                                             
        at utils.ScriptUtils$executeCommand$0.callStatic(Unknown Source)                                                                                                                               
        at upgrade-target.upgradeDB(upgrade-target.groovy:135)                                                                                                                                            
        at upgrade-target$upgradeDB$12.callCurrent(Unknown Source)                                                                                                                                    
        at upgrade-target.doUpgrade(upgrade-target.groovy:483)                                                                                                                                                                                                                 
        at upgrade-target$doUpgrade$4.callCurrent(Unknown Source)                                                                                                                                          
        at upgrade-target.upgrade(upgrade-target.groovy:497)                                                                                                                                                                                                                   
        at upgrade-target$upgrade$0.callCurrent(Unknown Source)                                                                                                                                
        at upgrade-target.run(upgrade-target.groovy:525)
```

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/MariaDB4j/pull/14
https://github.com/craftercms/studio/pull/1699
https://github.com/craftercms/craftercms/pull/3355

**Comment by yacdaniel** [comment]
@dejan-brkic I still see the error I posted in the comment above. Did you reproduce the issue following the upgrade guide? https://docs.craftercms.org/en/3.1/system-administrators/upgrade/index.html#upgrading-crafter-cms-installed-from-a-bundle

**Comment by dejan-brkic** [comment]
Latest error caused by old version DB still running after executing `crafter.sh stop`. Stopping DB manually (killing process) and running `post-upgrade.sh` works.

**Comment by yacdaniel** [comment]
Verified fixed.
