### ISSUE TITLE
[studio-ui] Users with access to Site Config should have access/permission to all modules inside Site Config

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#3427]
## Describe the bug
User belonging to group `site_developer` is not able to save changes to configuration files from `Site Config` -> `Configurations` and gets an `Error Code 2001: Unauthorized. You don't have permission to perform this task, please contact your administrator` when clicking on `Remote Repositories`

## To Reproduce
1. Create a user in Studio named `dev`
2. Add `dev` to the group `site_developer`
3. Create a site using the website editorial bp
4. Logout user `admin` then login as user `dev`
5. Open the `Sidebar` and click on `Site Config`
6. Click on `Configuration` then select any configuration from the dropdown
7. Make some edits to the config file, then click on the `Save` button
8. Notice the message: `Save Failed`
9. Look in the logs and notice the error
```
[ERROR] 2019-09-05T07:15:40,771 [http-nio-8080-exec-8] [v2.ExceptionHandlers] | API endpoint http://localhost:8080/studio/api/2/configuration/write_configuration?nocache=Thu%20Sep%2005%202019%2007:15:40%20GMT-0400%20(Eastern%20Daylight%20Time) failed with response: ApiResponse{code=2001, message='Unauthorized', remedialAction='You don't have permission to perform this task, please contact your administrator', documentationUrl=''}
org.craftercms.commons.security.exception.ActionDeniedException: Current subject does not have permission to execute action "write_configuration" on {siteId=anothersite}
```
10. Click okay on the notification dialog, then click on `Remote Repositories`
11. Notice the message: `Error Code 2001: Unauthorized. You don't have permission to perform this task, please contact your administrator`
12. Look in the logs and notice the error message there too.

## Expected behavior
Users with access to Site Config should have access to all modules inside Site Config

## Screenshots
Error message after clicking on `Remote Repositories`
<img width="1348" alt="Screen Shot 2019-09-05 at 7 22 41 AM" src="https://user-images.githubusercontent.com/25483966/64337801-17ad4000-cfae-11e9-9b2e-6eb0ccf34cdb.png">

Message after trying to save changes to a configuration file:
<img width="1347" alt="Screen Shot 2019-09-05 at 7 24 33 AM" src="https://user-images.githubusercontent.com/25483966/64337868-41fefd80-cfae-11e9-8a9a-79fff938b870.png">

## Logs
Here's a short clip performing the steps listed above:
https://www.loom.com/share/a2f37bcf291b4ce5b0adc35f7de01c49

### Version
Studio Version Number: 3.1.2-SNAPSHOT-1f0df9
Build Number: 1f0df9e38e6b916232af1299c06a6e21224f32f4
Build Date/Time: 09-04-2019 14:12:51 -0400

### OS
OS X

### Browser
Chrome browser

## Additional context
{{Add any other context about the problem here.}}

**Comment by sumerjabri** [comment]
@dejan-brkic much like what we did for the Main Menu, we should try the same here where we can have a permission set per tool. Let's discuss the API to return the SiteConfig tool list to the user as a future addition and perhaps put that in 3.1 or 3.2 (scheduling is a different matter).

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/video-center-blueprint/pull/60
https://github.com/craftercms/studio/pull/1747

**Comment by alhambrav** [comment]
Hi!
Verified developer user is now able to save changes in configuration files.

Regarding `Remote Repositories`, the user still does not have access (Click on `Remote Repositories`, then the error message below appears):
![Screen Shot 2019-09-19 at 10 57 34 AM](https://user-images.githubusercontent.com/25483966/65255741-6ee20300-dacc-11e9-910a-e62188b03ebd.png)

Studio version:
Studio Version Number: 3.1.4-SNAPSHOT-2a9aa4
Build Number: 2a9aa48efdd8dae37dac71a0c89e5214bca503c1
Build Date/Time: 09-19-2019 10:37:48 -0400

**Comment by dejan-brkic** [comment]
VC blueprint: https://github.com/craftercms/video-center-blueprint/pull/64

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/1759

**Comment by alhambrav** [comment]
Verified fixed
