### ISSUE TITLE
[studio] Can't encrypt configuration values as a `site_admin`

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4141]
## Describe the bug
When logged in as a `site_admin`, and you try to go into the `Site Config` of a site and encrypt with `Encrypt Marked`, Studio fails with an access denied error.

## To Reproduce
1. Login as a `site_admin`
2. Go into the `Site Config` > `Configurations` > `Engine Site Configuration`
3. Add an element with `encrypted=""` (e.g. `<test encrypted="">Hello</test>`)
4. Click on the `Encrypt Marker` button

You should see an error like in the screenshot

## Expected behavior
A `site_admin` or `developer` should be able to use `Encrypt Marked`

## Screenshots
![Screenshot from 2020-06-23 15-43-42](https://user-images.githubusercontent.com/1598884/85452746-31ce0400-b569-11ea-8c5b-603ad20f1f1b.png)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio-ui/pull/1819
https://github.com/craftercms/studio/pull/2044

https://github.com/craftercms/studio-ui/pull/1820
https://github.com/craftercms/studio/pull/2045

**Comment by avasquez614** [comment]
Tested in 3.1.x. Still happening when using a site created from the empty bp. Is it possible that the bp permission mappings need to be updated?

**Comment by dejan-brkic** [comment]
@avasquez614 none of the blueprints has that permission by default. It is added only as a global permission.

**Comment by sumerjabri** [comment]
@dejan-brkic 

Please do the following:
- [ ] Using the UM update existing sites to have the encryption capability for site admins and site developers
- [ ] Update built-in BPs to have that

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2048
https://github.com/craftercms/studio/pull/2049

**Comment by avasquez614** [comment]
Verified
