### ISSUE TITLE
[studio] In a Studio cluster, when saving a configuration file, just one of the nodes has the site context rebuilt

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4180]
## Describe the bug
Site context is only rebuilt in one of the nodes when saving a config file.

## To Reproduce
1. Set up a Studio cluster
2. Create a site based on our blob store test site (ping me for details and how to access it)
3. Go to Site Config > Configurations and open Site Configuration. Make small changes like adding XML comments, and save. At some point, you should see in the logs that the site context rebuilt message is only appearing in one node.

## Expected behavior
The site context should be rebuilt every time on both nodes. This doesn't seem to be happening in other simple sites like editorial.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2078
https://github.com/craftercms/studio/pull/2079

**Comment by avasquez614** [comment]
@dejan-brkic this issue is still happening, and I can actually reproduce it with a single Studio. But it only happens with the big repo test site I have. Ping me tomorrow and I'll show you and give you access to the repo.

**Comment by dejan-brkic** [comment]
Tried with VC blueprint. Can't reproduce it

**Comment by dejan-brkic** [comment]
With provided repo, still not able to reproduce. However, I have noticed many other issues that may be affecting that it appears as not working. Major issue is that actually create site dialog never closed (finished request). Besides, I have noticed that S3 was generating lots of errors and cluster sync looked like stopped working completely.

**Comment by avasquez614** [comment]
Thanks @dejan-brkic. The first one (create site dialog) it's a known issue when a site takes too long to create. The other ones is probably then what I saw. If they're unrelated issues, can you please file tickets for them? I'll close this issue after that.

**Comment by avasquez614** [comment]
Closed, will discuss the other issues and file appropriate tickets.
