### ISSUE TITLE
[studio] Get children by * issues

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4359]
- [x] Items that don't have a content type, like folders (e.g. /site/website/articles) still show a `contentTypeId` prop value (e.g. `"contentTypeId": "page"`). It should be null.
- [x] Page-type items have `systemType` of "file". Should be "page"?
- [x] `commitID` prop value is "HEAD". Is that correct?
- [x] Won't fix, this is correct -- `"sizeInBytes": 0` for folders
- [x] `disabledAsInt` is not part of SandboxItem interface. Remove prop.
- [x] `previewUrl` for previewable items (pages) is coming as the full path (e.g. `/site/website/entertainment/index.xml` instead of `/entertainment`) -- remove leading `/site/website` and trailing `/index.xml`
- [x] For non-previewable items, `previewUrl` should be null. Examples of non-navigable items
  - Rule: previewable is `/site/website` and `/static-assets` <== this is configurable (including static-assets MIME-types, see older work/config in site-config.xml)
  - [x] Folders
  - [x] Some static assets (non-previewable)
- [x] Won't fix, this is correct (sometimes the creator/modifier is unknown, find a way to represent it on the UI) -- `creator` & `modifier` props are null
- [x] `label` prop, on certain pages is `index.xml` instead of the content title (i.e. internal name)
- [x] `mimeType` for `/static-assets/images` — a folder — is coming as "image/jpeg"

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2353

**Comment by rart** [comment]
Issues found:

- [ ] Added an internal-name to a level desc xml and label still shows null
- [ ] System type is null in various cases
  - [ ] level descriptor
  - [ ] pages
  - [ ] components
  - [ ] stopped testing here, possibly all but folders are incorrect
- [ ] Components, including level descriptors, have a preview url
- [ ] `/site/taxonomy` has a previewUrl of `/site`. `/site/website/articles` has a previewUrl of `/site/website`. These are incorrect. In the case of taxonomy, it shouldn't even have one.
- [ ] Requesting a path that doesn't exist returns the same 200 as if it did, should it return 404 or otherwise?
- [ ] Folders show label = null. Could we have the folder name?
- [ ] item_by_path endpoint it's 404ring and it doesn't even return json

**Comment by rart** [comment]
Verified
