### ISSUE TITLE
[studio] Rename Issue with GetChildrenByPath

### ISSUE THREAD

**Issue by aachavarria** [craftercms/craftercms#4481]
## Describe the bug
When you rename a folder, a new folder is created with the new name, but the previous one is still present on the response from GetChildrenByPath

## To Reproduce
1. Create a new Editorial Site
2. Go to Path Navigator and rename Articles forder
3. See the list of items on the Path 'Home'
4. There are 2 Articles Folder

## Expected behavior
Should only be 1 Article Folder with the new name

## Screenshots
<img width="244" alt="Captura de Pantalla 2021-01-22 a la(s) 14 41 07" src="https://user-images.githubusercontent.com/10813283/105543831-e1b24e00-5cbf-11eb-8836-a78ea0e7b231.png">
<img width="589" alt="Captura de Pantalla 2021-01-22 a la(s) 14 41 28" src="https://user-images.githubusercontent.com/10813283/105543880-eecf3d00-5cbf-11eb-9c32-76a9f93ec413.png">

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version

Studio Version Number: 4.0.0-SNAPSHOT-d99795

Build Number: d99795680a9de37c090bb2a9bff9caf341b09d20

Build Date/Time: 01-22-2021 10:11:26 -0600

### OS
macOS Catalina 10.15.7

### Browser
Chrome 87.0.4280.141

## Additional context
{{Add any other context about the problem here.}}

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2366

**Comment by aachavarria** [comment]
@dejan-brkic Im still having issues:
There are no additional Folders and that is fine, but the edited folder still have the old label. See the following.
However the path is changed, but the label is wrong
 
<img width="576" alt="Captura de Pantalla 2021-01-27 a la(s) 15 40 36" src="https://user-images.githubusercontent.com/10813283/106057860-2706bf00-60b6-11eb-8465-1adc1c0066dd.png">

**Comment by dejan-brkic** [comment]
Fixed here
https://github.com/craftercms/craftercms/issues/4508

**Comment by aachavarria** [comment]
Verified.
