### ISSUE TITLE
[studio-ui] Top toolbar may not update on time when navigating via preview

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4810]
## Describe the bug
When navigating on the preview, the top toolbar updates after an item retrieval service responds, and meanwhile the topbar stays outdated (with the previous item). So, if there's a delay in the service response, and you click for example on 'Edit', the edit form will open the previous page.

## To Reproduce
1. Go to Editorial bp based site (preview).
2. To simulate a slow response, use network throttling on developer tools, or add a timeout in host.js lookupContentItem service call.
3. Navigate using the site navigation.
4. Click on 'Edit'.
5. See that the form opens the previous page content.

## Expected behavior
The topbar should be disabled while retrieving the new item, so that way the user will have a visual feedback to know that the bar cannot be used until it loads the item.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
{{If applicable, attach the logs/stack trace (use https://gist.github.com).}}

### Version
v3.1.15-SNAPSHOT

### OS
{{What OS did you use to produce the bug.}}

### Browser
{{What browser did you use to produce the bug.}}

## Additional context
{{Add any other context about the problem here.}}

**Comment by jvega190** [comment]
@yacdaniel assigning it to you for validation, you may need to set a breakpoint and network throttling for it to be validated, please ping me for help if needed

**Comment by yacdaniel** [comment]
As the delay in the service response might come from different reasons(network) some cases might be tricky and difficult to reproduce/fix. Closing as fixed in `3.1.16-SNAPSHOT` with the basic scenario described in the ticket.

**Comment by rart** [comment]
@jvega190 this still happens when there's a large payload on the iframe site. Please send a GUEST_CHECK_OUT event onbeforeunload on the guest that notifies host when a page is checkout out to disable nav while new page checks in.

**Comment by rart** [comment]
@yacdaniel we want to include this in 3.1.18. please have a look when you get a chance.

**Comment by yacdaniel** [comment]
Verified fixed in 3.1.18
