### ISSUE TITLE
[studio] Committing a file, then doing several edits, and then committing again, leaves the published folder in a conflict state

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#952]
Steps to reproduce:

- Create a site with editorial.
- Make a change in a page.
- Publish the page.
- Make a change and save the page. Repeat several times so that there are several commits in the sanbox repo.
- Publish the page.

The result is that the published folder has a conflict: 

```
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)
You are currently cherry-picking commit de5490c.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   site/website/style/index.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

This seems to be solved by cherry-picking the commits after the first one. So the solution might be that Studio needs to cherry-pick all unpublished commits instead of the last one.

**Comment by dejan-brkic** [comment]
Done

PR:
https://github.com/craftercms/studio/pull/739

**Comment by avasquez614** [comment]
Tested and fix seems to work.

**Comment by avasquez614** [comment]
This seems to be still happening with a particular case:

1. Make a change.
2. Publish -> Works.
3. Make a change.
4. Make a change.
5. Publish -> Works.
6. Make a change.
7. Make a change.
8. Make a change.
9. Publish -> Git cherry-pick conflict in published.

Besides that I noticed that a comment seems to have been modified and left like this:

```
    ~~ Crafter Studio - commit ID = 74af06e27a3418aa7911b356843e6f80b3f800cf ~~
    ----------------------------------
    ~~ Crafter Studio - commit ID = 74af06e27a3418aa7911b356843e6f80b3f800cf ~~
    ----------------------------------
    Wrote content /site/website/style/index.xml
```
So maybe there's something wrong with how the message is parsed? The Tomcat log also shows the following:

```
[ERROR] 2017-06-18 14:45:43,492 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Conflict executing cherry-pick null 
[ERROR] 2017-06-18 14:45:43,497 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Cherry-pick failed {site/website/style/index.xml=DIRTY_INDEX} and arguments [Ljava.lang.Object;@6ba5efff failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/index.xml=DIRTY_INDEX 
[ERROR] 2017-06-18 14:45:43,501 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Cherry-pick failed {site/website/style/index.xml=DIRTY_INDEX} and arguments [Ljava.lang.Object;@501d6696 failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/index.xml=DIRTY_INDEX 
[ERROR] 2017-06-18 14:45:43,507 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Cherry-pick failed {site/website/style/index.xml=DIRTY_INDEX} and arguments [Ljava.lang.Object;@29e7e55a failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/index.xml=DIRTY_INDEX 
[ERROR] 2017-06-18 14:45:43,511 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Cherry-pick failed {site/website/style/index.xml=DIRTY_INDEX} and arguments [Ljava.lang.Object;@3bd10af0 failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/index.xml=DIRTY_INDEX 
[ERROR] 2017-06-18 14:45:43,517 [studioSchedulerFactoryBean_Worker-9] [git.GitContentRepository] | Cherry-pick failed {site/website/style/index.xml=DIRTY_INDEX} and arguments [Ljava.lang.Object;@7f4fc062 failed to expand in to message java.lang.IllegalArgumentException: can't parse argument number: site/website/style/index.xml=DIRTY_INDEX 
```

**Comment by avasquez614** [comment]
Same thing when you do this:

1. Make a change.
2. Publish.
3. Make a change.
4. Publish
5. Make a change.
6. Publish.

The published folder is left in conflict and the weird double message appears again.

**Comment by sumerjabri** [comment]
@avasquez614 we have a fix in place, but it's not the long-term: changes include:

1. switch to -x
2. block on failure and allow sysadmin to fix by hand
3. continue after they fix

**Comment by dejan-brkic** [comment]
Done
PR

https://github.com/craftercms/studio/pull/751

**Comment by avasquez614** [comment]
Tested and verified that it's working.
